# Generated by Django 2.0.13 on 2020-08-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='premier_league',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('point', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('play', models.IntegerField(default=0)),
                ('gdp', models.IntegerField(default=0)),
            ],
        ),
    ]
