# Generated by Django 2.0.13 on 2020-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_premier_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='premier_league',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
