# Generated by Django 2.0.13 on 2020-08-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_premier_league_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='premier_league',
            name='idx',
            field=models.CharField(default='', max_length=200),
        ),
    ]
