# Generated by Django 2.0.13 on 2020-08-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_premier_league_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premier_league',
            name='idx',
            field=models.CharField(default='normal', max_length=200),
        ),
    ]
