# Generated by Django 2.0.13 on 2020-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
