# Generated by Django 2.0.13 on 2020-08-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_news_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_index',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
